app:
  browser:
    name: chrome
    remote: false
    remoteServerAddress: http://localhost:4444/wd/hub
    resolution:
      width: 1920
      height: 1080
    headless: false
    timeout:
      implicit: 10s
      explicit: 10s
      polling: 500ms
spring:
  profiles:
    active: prod
